project_id = "eexxmfuknqttujecbcho"

[functions.send-health-notification]
verify_jwt = false

[functions.search-usda-foods]
verify_jwt = false

[functions.analyze-food-photo]
verify_jwt = false

[functions.seed-health-data]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
